
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";
import { SuspenseWrapper } from "./prod-components/SuspenseWrapper";

const App = lazy(() => import("./pages/App.tsx"));

export const userRoutes: RouteObject[] = [
	{
		path: "/",
		element: (
			<SuspenseWrapper>
				<App />
			</SuspenseWrapper>
		),
	},
];
